import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import PostInput from "@/components/Post/PostInput";
import PostList from "@/components/Post/PostList";
import { getAccessToken } from "@auth0/nextjs-auth0";
import { GetServerSideProps, GetServerSidePropsContext } from "next";
import axios from "axios";
import { Post } from "@/interfaces/post.interface";
import buildClient from "./api/build-client";

const inter = Inter({ subsets: ["latin"] });

interface HomeProps {
  posts: Post[];
}

export const Home: React.FC<HomeProps> = ({ posts }) => {
  return (
    <>
      <Head>
        <title>Friends Club</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PostInput />
        <PostList posts={posts} />
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps<HomeProps> = async (
  ctx: GetServerSidePropsContext
) => {
  const { accessToken } = await getAccessToken(ctx.req, ctx.res);
  const client = buildClient(ctx);
  const { data: posts } = await client.get("/api/post", {
    headers: { Authorization: `Bearer ${accessToken}` },
  });

  return {
    props: {
      posts: posts,
    },
  };
};

export default Home;
